export const LIMIT_PAGE = 20;
export const MAX_PAGE_NUMBER = 180;
export const START_PAGE_NUMBER = 1;
export const DEFAULT_PAGE_SIZE = 30;

export const DEFAULT_PAGINATION_OFFSET = 0;
export const DEFAULT_LANGUAGE = 'English';
export const DEFAULT_LANGUAGE_CODE = 'en';
export const DEFAULT_CATEGORIES = 'general';
export const DEFAULT_REGION = 'International';

export const CATEGORIES = [
  'regional',
  'technology',
  'lifestyle',
  'business',
  'general',
  'programming',
  'science',
  'entertainment',
  'world',
  'sports',
  'finance',
  'academia',
  'politics',
  'health',
  'opinion',
  'game',
  'fashion',
  'academic',
  'crap',
  'travel',
  'culture',
  'economy',
  'environment',
  'art',
  'music',
  'notsure',
  'CS',
  'education',
  'redundant',
  'television',
  'commodity',
  'movie',
  'entrepreneur',
  'review',
  'auto',
  'energy',
  'celebrity',
  'medical',
  'gadgets',
  'design',
  'EE',
  'security',
  'mobile',
  'estate',
  'funny',
];

export const REGIONS = [
  'Australia',
  'Canada',
  'China',
  'Finland',
  'South Korea',
  'Taiwan',
  'Thailand',
  'Vietnam',
  'United State',
  'German',
  'Zimbabwe',
  'Italy',
  'United Kingdom',
  'India',
  'Spain',
  'Poland',
  'Malaysia',
  'Singapore',
  'Denmark',
  'France',
  'Belgium',
  'Japan',
  'Austria',
  'Portugal',
  'Philippines',
  'Hong Kong',
  'Argentina',
  'Venezuela',
  'Brazil',
  'Indonedia',
  'Mexico',
  'Greece',
  'Netherlands',
  'Norway',
  'New Zealand',
  'Russia',
  'Saudi-Arabia',
  'Switzerland',
  'United Arab Emirates',
  'Ireland',
  'Iran',
  'Iraq',
  'Romania',
  'Afghanistan',
  'Myanmar',
  'Sweden',
  'Peru',
  'Panama',
  'Egypt',
  'Turkey',
  'Israel',
  'Czech Republic',
  'Bangladesh',
  'Nigeria',
  'Kenya',
  'Chile',
  'Uruguay',
  'Ecuador',
  'Serbia',
  'Hungary',
  'Slovenia',
  'Gahana',
  'Bolivia',
  'Pakistan',
  'Colombia',
  'North Korea',
  'Paraguay',
  'Palestine',
  'Estonia',
  'Lebanon',
  'Qatar',
  'Kuwait',
  'Cambodia',
  'Nepal',
  'Luxembourg',
  'Bosnia',
  'Europe',
  'Asia',
  'International',
];

export const REGIONS_CODE = {
  Australia: 'AS',
  Canada: 'CA',
  China: 'CN',
  Finland: 'FI',
  'South Korea': 'SK',
  Taiwan: 'TW',
  Thailand: 'TH',
  Vietnam: 'VIET',
  'United State': 'US',
  German: 'GB',
  Zimbabwe: 'ZW',
  Italy: 'IT',
  'United Kingdom': 'GB',
  India: 'IN',
  Spain: 'ES',
  Poland: 'PL',
  Malaysia: 'MY',
  Singapore: 'SG',
  Denmark: 'DK',
  France: 'FR',
  Belgium: 'BE',
  Japan: 'JP',
  Austria: 'AT',
  Portugal: 'PT',
  Philippines: 'PH',
  'Hong Kong': 'HK',
  Argentina: 'AR',
  Venezuela: 'VE',
  Brazil: 'BR',
  Indonedia: 'ID',
  Mexico: 'MX',
  Greece: 'GR',
  Netherlands: 'NL',
  Norway: 'NO',
  'New Zealand': 'NZ',
  Russia: 'RU',
  'Saudi-Arabia': 'SA',
  Switzerland: 'CH',
  'United Arab Emirates': 'AE',
  Ireland: 'IE',
  Iran: 'IR',
  Iraq: 'IQ',
  Romania: 'RO',
  Afghanistan: 'AF',
  Myanmar: 'MM',
  Sweden: 'SE',
  Peru: 'PE',
  Panama: 'PA',
  Egypt: 'EG',
  Turkey: 'TR',
  Israel: 'IL',
  'Czech Republic': 'CZ',
  Bangladesh: 'BD',
  Nigeria: 'NG',
  Kenya: 'KE',
  Chile: 'CL',
  Uruguay: 'UY',
  Ecuador: 'EC',
  Serbia: 'RS',
  Hungary: 'HU',
  Slovenia: 'SI',
  Gahana: 'GH',
  Bolivia: 'BO',
  Pakistan: 'PK',
  Colombia: 'CO',
  'North Korea': 'NK',
  Paraguay: 'PY',
  Palestine: 'PS',
  Estonia: 'EE',
  Lebanon: 'LB',
  Qatar: 'QA',
  Kuwait: 'KW',
  Cambodia: 'KH',
  Nepal: 'NP',
  Luxembourg: 'LU',
  Bosnia: 'BA',
  Europe: 'EU',
  Asia: 'ASIA',
  International: 'INT',
};

export const LANGUAGES = [
  'Arabic',
  'Chinese',
  'Dutch',
  'English',
  'Finnish',
  'French',
  'German',
  'Hindi',
  'Italian',
  'Japanese',
  'Korean',
  'Malay',
  'Portuguese',
  'Russian',
  'Spanish',
];

export const LANGUAGES_CODE = {
  Arabic: 'ar',
  Chinese: 'zh',
  Dutch: 'nl',
  English: 'en',
  Finnish: 'fi',
  French: 'fr',
  German: 'de',
  Hindi: 'hi',
  Italian: 'it',
  Japanese: 'ja',
  Korean: 'ko',
  Malay: 'msa',
  Portuguese: 'pt',
  Russian: 'ru',
  Spanish: 'es',
};
