export type Category =
  | 'general'
  | 'sports'
  | 'business'
  | 'entertainment '
  | 'health '
  | 'science '
  | 'technology '
  | 'regional'
  | 'lifestyle'
  | 'programming'
  | 'world'
  | 'finance'
  | 'academia'
  | 'politics'
  | 'opinion'
  | 'food'
  | 'game';
